### ISSUE TITLE
:bulb: Data et interop :people_holding_hands: 

### ISSUE THREAD

**Issue by adriens** [ZoeThivet/epic-win#1]
# :grey_question: Contexte

De premiers contenus sont disponibles sur cette repo, mais ils ne sont pas interopérables : par exemple on peut pas les charger dans une base de donées, les exposer en API, faire de la datascience dessus, une app mobile,etc....

# :bulb: Idée

Disposer ces idées sous forme de `csv` ou `yaml`par exemple au lieu d'un markdown non structuré... par exemple tu pourrais même construire/builder un site web statique qui consommerait ces donnée :point_right:  [avec Jekyll cela se fait très bien.](https://jekyllrb.com/docs/datafiles/)

![image](https://user-images.githubusercontent.com/5235127/212779063-2c31d8f7-8ca7-444c-b3e9-7fa691faa0c9.png)

**Comment by ZoeThivet** [comment]
Effectivement, pour le moment ça a juste pour objectif de présenter une liste (pas trop moche, d'où le markdown)
Mais j'ai une idée en tête qui nécessitera sans doute d'en faire des données structurées...
Merci pour ton retour et ton conseil !

**Comment by adriens** [comment]
> Mais j'ai une idée en tête qui nécessitera sans doute d'en faire des données structurées...

LOL, tu me teases bien. :star_struck:

**Comment by ZoeThivet** [comment]
@adriens Je t'en dirai + quand je m'y mettrai 😎 

Je réfléchis à ta suggestion et je me pose la question : ce serait quoi le mieux pour ce type de csv, sachant que pour certains termes il y a plusieurs traductions possibles ?

Terme,Traduction 1,Traduction 2,Traduction 3,Etc ?

Ou plutôt

Terme,Traduction 1
Terme,Traduction 2
Etc ?

(Je penche plutôt vers la 2ème solution...)

**Comment by adriens** [comment]
... ou :

- `fichier_EN.csv`
- `ficher_FR.csv` 

Pour les contributions c super facile à gérer...et pout `i18n` aussi :thinking:

**Comment by ZoeThivet** [comment]
@adriens ha non je ne parlais pas des traductions vers des autres langues, mais des "traductions" entre langage genré et non genré, j'aurais dû mettre un exemple ^^

Terme genré,Terme épicène 1,Terme épicène 2
Utilisateur,Membre,Personne

Ou

Terme genré,Terme épicène
Utilisateur,Membre
Utilisateur,Personne

(Pour convertir en csv le fichier codex.md de ce projet)

**Comment by adriens** [comment]
```
Terme genré,Terme épicène
Utilisateur,Membre
Utilisateur,Personne
```

me semble super simple :+1:
