### ISSUE TITLE
❓ Trouver une traduction pour "joueur" ⛹️‍♀️

### ISSUE THREAD

**Issue by ZoeThivet** [ZoeThivet/epic-win#11]
Par quel mot épicène pourrait-on remplacer "joueur" ?
De jeux vidéo notamment

**Comment by ZoeThivet** [comment]
(Pour https://gitlocalize.com/repo/6994/fr/en.json)

**Comment by adriens** [comment]
Challenge comme question :thought_balloon:

**Comment by adriens** [comment]
"Gamer" ?... mais en français on a créé "Gameuse" ;-(

**Comment by adriens** [comment]
"Fan de jeux vidéo"  :grey_question:

**Comment by ZoeThivet** [comment]
@adriens Oui comme dans beaucoup de cas, c'est tentant d'utiliser la traduction anglaise ! J'utilise cette botte secrète pour parler des "crowdtesters" ;)
Fan de jeux vidéos ça fonctionne dans certains cas c'est vrai, je l'ajouterai dans la liste.
Sinon peut-être "membre" ou "personne" comme d'hab mais j'aurais voulu trouver un truc un peu plus ludique...
J'espère que je trouverai une réponse dans mon sommeil 🤓 🌔

**Comment by Berny911Git** [comment]
Je propose "**qui aime jouer**", ce qui somme toute pourrait assez bien correspondre aux "Fan de jeux vidéo", "membres de la communauté gamer" ou "personnes très très très engagées dans l'aspect le plus ludique du monde informatique" lol. 

Sinon si le contexte s'y prête, peut-être "**partenaire de jeu**"?

**Comment by adriens** [comment]
EN tout cas, cette ssue n'est vraiment pas facile, c'est un vrai challenge :open_mouth:

**Comment by Berny911Git** [comment]
@adriens : Oui, le défi est de taille!!!! Mais c'est très intéressant ;-) 

@ZoeThivet & @adriens : Je viens de penser à un autre mot qui comme les autres porte forcément une nuance un peu différente de "joueurs et joueuses" mais qui a l'avantage d'être épicène : "**adeptes**"... pas facile et comme les autres propositions, jamais totalement convaincant... On continue de prendre plaisir à jouer!!!

**Comment by adriens** [comment]
Adepte, pour fan, mais oui :heavy_heart_exclamation:  Bien joué :clap:

**Comment by MF2G-JULIEN** [comment]
« Tripoteur de variables » 🤷‍♂️

**Comment by MF2G-JULIEN** [comment]
Ou « buger » ou hors gaming je dirais « chercheur en sensations »

**Comment by MF2G-JULIEN** [comment]
Sinon de façon littérale j’en propose deux:
74 111 117 101 117 114 
Sm91ZXVy

**Comment by meumsy** [comment]
Proposition de méthodologie : lister les synonymes sans se préoccuper de genre, ici utilisat.eur.rice, protagoniste, combatant.e (j'y connais rien en jeu vidéo), filtrer les épicènes, choisir le meilleur, s'il n'est pas assez satisfaisant se diriger vers une locution (qui nécessite une sous méthode)

**Comment by meumsy** [comment]
Dans une interface une locution me paraît peu ergonomique. On peut trouver des mots épicènes plus spécifiques, pour chaque type de jeu : personnage, protagoniste, pilote, stratège... Si on veut absolument conserver la précision de joueur, il y a aussi la solution du néologisme : jocariste, ludophile, ludonaute...

Ah, ludophile existe en fait, mais c'est trop passif. Il y a la notion d'acteur dans jocariste mais c'est pas très sexy comme mot

**Comment by meumsy** [comment]
Existe déjà mais utile dans certains cas : manette 1, manette 2... clavier 1, clavier 2

**Comment by ZoeThivet** [comment]
@meumsy hé c'est top "stratège" !! J'aime bien aussi protagoniste.
Manette & clavier c'est sympa aussi, ça me rappelle la traduction "plume" que j'avais vue pour "auteur/autrice" -> parler par métonymie en évoquant l'outil utilisé.
Je vais rajouter ça aux procédés !! :)

**Comment by ZoeThivet** [comment]
@adriens en te relisant j'ai un anglicisme qui m'est venu : "challenger" !
Même si à l'oral on entend "eur" et qu'on a envie de dire aussi "challengeuse" ^^

**Comment by meumsy** [comment]
@ZoeThivet c'est bien en lisant plume que je me suis rappelé de ça

**Comment by meumsy** [comment]
Machine, console, avatar

**Comment by meumsy** [comment]
Cerveau, personnalité, esprit, système nerveux, incarnation

**Comment by meumsy** [comment]
Jeu-videaste, pilote de jeu/partie, rôliste

**Comment by adriens** [comment]
> Même si à l'oral on entend "eur" et qu'on a envie de dire aussi "challengeuse"

Pas faux :smile_cat:

**Comment by ZoeThivet** [comment]
Je clôture car plusieurs traductions satisfaisantes ont été trouvées ! :)

**Comment by adriens** [comment]
:clap:
