### ISSUE TITLE
Erreur rencontrée lors de l'activation de l'extension en cliquant sur la framboise

### ISSUE THREAD

**Issue by Berny911Git** [ZoeThivet/epic-win#12]
Très chers adeptes ;-)

L'installation de l'extension se déroule parfaitement, mais rien de semble se passer lorsque l'on clique sur la framboise...

Dans la console développeur, voici le problème rencontré, reproductible sur n'importe quelle page html et sous différents navigateurs basés sur chrome:

![Erreur extension Epic-win](https://user-images.githubusercontent.com/118412132/222705879-5bf10950-eaae-4ff6-922d-3ca49f525055.png)

Ce qui est bizarre, c'est que le fichier dictionary.csv est bien déclaré dans le Manifest / web_accessible-resources...

Serait-ce la syntaxe du chemin qui est en cause ou une autorisation à déclarer?!?

**Comment by adriens** [comment]
:open_mouth:

**Comment by ZoeThivet** [comment]
(J'ai vu mais j'ai pas encore pris le temps d'étudier ce bug 8) )

**Comment by adriens** [comment]
Bug pas fixé du coup ?

**Comment by ZoeThivet** [comment]
@adriens non, wontfix, je me concentre sur la traduction et j’abandonne l’extension :D

**Comment by adriens** [comment]
AH yes, focus que la qualité, :+1:
