### ISSUE TITLE
:art: Repository's social media preview :gift: 

### ISSUE THREAD

**Issue by adriens** [ZoeThivet/epic-win#7]
# :grey_question: A propos

Créer le [social preview d'une repo](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/customizing-your-repositorys-social-media-preview) permet de mieux la partager sur les réseaux sociaux.

# :dart: Action

- [x] Proposer une composition originale à la bonne défintion
- [x] Configurer le social preview
- [x] Faire le test sur  linkedIn
- [x] Faire le test sur Twitter
- [x] Faire le test sur Facebook

**Comment by adriens** [comment]
:bulb: Une proposition : 

![zoe-thivet-epic-win](https://user-images.githubusercontent.com/5235127/214163483-2ef2014a-dd94-4aa1-ba3e-aaff2f7d68e7.png)

**Comment by adriens** [comment]
Tu me diras ce que tu en penses. J'ai voulu la chose assez symbolique... j'espère que ça te plaira :sweat_smile:

**Comment by ZoeThivet** [comment]
@adriens hé c'est top ! La photo est libre de droits ? (Chuis sûre que oui, just checking ^^)
Je me penche sur le tuto histoire de cocher toutes ces cases 😌✨ 
Merci pour cette bonne idée !!

**Comment by adriens** [comment]
> Chuis sûre que oui, just checking ^^)

Yep, et générée par de l'IA :smile_cat:

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/214253320-d0879edb-f084-4122-acf1-32f2ef15f0e4.png)

**Comment by ZoeThivet** [comment]
✅ Test LinkedIn : 

![image](https://user-images.githubusercontent.com/15658793/214251603-24c6dadf-e9f5-4269-873a-07e429a0f982.png)

🚫 Test Twitter : 

![image](https://user-images.githubusercontent.com/15658793/214252678-f57e75eb-5e69-4f7f-9f8d-69f81e97850f.png)

✅ Test Facebook :

![image](https://user-images.githubusercontent.com/15658793/214251450-b9cb6e4c-8a2c-4bd0-95a0-0ffd6bcea550.png)

Un trick pour rafraîchir la preview : https://www.linkedin.com/post-inspector/

Mais après coup @adriens, comme le repo est 100 % en français, il vaudrait mieux que la preview soit aussi en français ! Tu as la possibilité de faire une V2 stp ? 😃 

Que penses-tu du texte "Qu'il est bon de manger épicène !" ? 😂

**Comment by adriens** [comment]
> as la possibilité de faire une V2 stp ?

Of course, donne moi le texte et c parti :zap:

**Comment by ZoeThivet** [comment]
@adriens "Construire un wording simple et inclusif" 😎

**Comment by adriens** [comment]
![Memorable design](https://user-images.githubusercontent.com/5235127/214268558-90d88e2a-eb01-469c-97db-60615d74f54e.png)

**Comment by ZoeThivet** [comment]
@adriens mince j'avais pas eu la notif !! Merci beaucoup, je fais la MAJ 😎

**Comment by adriens** [comment]
:ok_hand: [Test complets du preview sur `https://www.opengraph.xyz`](https://www.opengraph.xyz/url/https%3A%2F%2Fgithub.com%2FZoeThivet%2Fepic-win%2F) : 


![image](https://user-images.githubusercontent.com/5235127/215317174-909b7d3f-1b07-4313-b906-019b278774c3.png)
![image](https://user-images.githubusercontent.com/5235127/215317183-c6d1f157-6197-40b9-90dd-c77dfc588528.png)
![image](https://user-images.githubusercontent.com/5235127/215317191-c7429f74-b71a-47f4-8738-b50b74f2d2f4.png)
