### ISSUE TITLE
dictionary.csv > Aouter un header

### ISSUE THREAD

**Issue by adriens** [ZoeThivet/epic-win#8]
Actuellement [`resources/dictionary.csv`](https://github.com/ZoeThivet/epic-win/blob/main/resources/dictionary.csv) n'a pas de header alors que cela est une bonne pratique.

**Comment by ZoeThivet** [comment]
Il faudra pour ça que je change un truc dans l'extension pour qu'elle ignore le header (je le ferai pas tout de suite tout de suite pour cette raison :p)

**Comment by adriens** [comment]
Ahhhhh :+1:
